### PR TITLE
Change mappings to reflect discontinuation of CentOS Core

### LINKED ISSUE #73: [BUGFIX] Change  `'centos'` mappings to `'cs'`  mappings in the `scap/oscap/map.jinja` file
With the complete discontinuation of EL7 and change from CentOS (Core) to CentOS Stream, mappings should be changed from `'centos'` mappings to `'cs'`  mappings in the `scap/oscap/map.jinja` file

See [watchmaker-salt-content #44](https://github.com/plus3it/watchmaker-salt-content/issues/44) for reference

### PR DESCRIPTION
**Pull request by ferricoxide**
closes #73

### CODE REVIEW

**Review by lorengordon — COMMENTED** [review]
May as well remove the content for centos7 and centos8 while you're in here. Make it really official.

**Comment by ferricoxide** [comment]
@lorengordon sed:
> May as well remove the content for centos7 and centos8 while you're in here. Make it really official.

Only potentially relevant files are:

* `scap/oscap/map.jinja`: Changes made in ae3b405
* `tests/docker/centos7/Dockerfile`: Presumably this needs to be wholly replaced with an Alma reference? If so, "what changes to make"
* `README.md`: No explicit reference to CentOS 7 or CentOS Stream 8
* `scripts/build_ssg_content.sh`: Changes made in e363232
* `.travis.yml`: Are we even using this, any more? If so, "what changes to make"

**Comment by lorengordon** [comment]
> @lorengordon sed:
> 
> > May as well remove the content for centos7 and centos8 while you're in here. Make it really official.
> 
> Only potentially relevant files are:
> 
> * `scap/oscap/map.jinja`: Changes made in [ae3b405](https://github.com/plus3it/scap-formula/commit/ae3b40510dc8b06ffc9a10aab7ef39d60efe9a7d)
> * `tests/docker/centos7/Dockerfile`: Presumably this needs to be wholly replaced with an Alma reference? If so, "what changes to make"
> * `README.md`: No explicit reference to CentOS 7 or CentOS Stream 8
> * `scripts/build_ssg_content.sh`: Changes made in [e363232](https://github.com/plus3it/scap-formula/commit/e363232719efde10b9691ab9b19a8a420ea00a12)
> * `.travis.yml`: Are we even using this, any more? If so, "what changes to make"

There's also the content under `scap/content/guides`
* `[stig-el7-scap_1-2.xml](https://github.com/plus3it/scap-formula/blob/master/scap/content/guides/disa/stig-el7-scap_1-2.xml)
* [ssg-centos7-ds.xml](https://github.com/plus3it/scap-formula/blob/master/scap/content/guides/openscap/ssg-centos7-ds.xml)
* [ssg-centos7-xccdf.xml](https://github.com/plus3it/scap-formula/blob/master/scap/content/guides/openscap/ssg-centos7-xccdf.xml)
* [ssg-centos8-ds.xml](https://github.com/plus3it/scap-formula/blob/master/scap/content/guides/openscap/ssg-centos8-ds.xml)
* [ssg-centos8-xccdf.xml](https://github.com/plus3it/scap-formula/blob/master/scap/content/guides/openscap/ssg-centos8-xccdf.xml)

**Comment by lorengordon** [comment]
> 
> * `.travis.yml`: Are we even using this, any more? If so, "what changes to make"

Yes, this project is still using travis-ci. The failure is the same as it was on watchmaker, where centos7 is no longer available. But, oof. The ci was never even updated for EL8, much less EL9. Got some work to do there :(

**Comment by ferricoxide** [comment]
@lorengordon sed:
> …The failure is the same as it was on watchmaker, where centos7 is no longer available. But, oof. The ci was never even updated for EL8, much less EL9. Got some work to do there :(

Ok. Given the markedly different focus of that work (and that it's not a simple, "while you're there" kind of task), seems like that should be a separate [issue](https://github.com/plus3it/scap-formula/issues/new), no? 

Basically, I'm out the door for a week in about 30 minutes. Either this entire PR waits till I return, or we get the actual _functionality_ out the door before I duck. What's in this PR is the functionality that this ticket was created to address …just that the CI is is massively stale.

**Comment by lorengordon** [comment]
>Ok. Given the markedly different focus of that work (and that it's not a simple, "while you're there" kind of task), seems like that should be a separate [issue](https://github.com/plus3it/scap-formula/issues/new), no?

The CI probably should be fixed in a separate PR, but it's gonna block merges until the CI setup is updated. The checks are doing important things.

**Comment by ferricoxide** [comment]
@lorengordon 

I'm assuming that this PR has is now OBE by a different PR? Can you link that PR into a closing-comment on this PR?

**Comment by lorengordon** [comment]
> @lorengordon
> 
> I'm assuming that this PR has is now OBE by a different PR? Can you link that PR into a closing-comment on this PR?

No, this is the active PR.

**Comment by lorengordon** [comment]
@plus3it/salt-formulas Alright, this is ready for a look. Tests now exercise both EL8 and EL9, and all the EL7 references have been removed.

**Comment by lorengordon** [comment]
Realized we couldn't _entirely_ remove the `centos8` content, since at least notionally we were support Rocky8 and Alma8 and mapping them to the centos8 content...

**Review by eemperor — APPROVED** [review]

**Pull request merged**
